version: '3.8'

services:
  employeemanagement:
    image: employeemanagement:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: employeemanagement
    ports:
      - "8080:8080" 
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/employeedb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=asma1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQL8Dialect
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: employeedb
    ports:
      - "3306:3306"  
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
    driver: local
